get_last_dirname(${CMAKE_CURRENT_SOURCE_DIR} ADDON_DIRNAME)

set(ADDON_CMAKE_DIR ${CMAKE_SOURCE_DIR}/${ADDON_DIRNAME})
set(ADDON_LIBS_DIR ${CMAKE_SOURCE_DIR}/libs)
set(ADDON_SOURCE_DIR ${CMAKE_SOURCE_DIR}/src)